"""test_net_proxy.py — TDD tests for OSM-scoped proxy auto-detection.

openstreetmap.org is unreachable by direct connection from mainland-China
networks. The GUI (launched from a desktop shell with no http_proxy env) must
auto-discover a local Clash-style proxy and use it for OSM requests ONLY —
never globally, or LAN collab sync would be routed into the proxy too.

No real network: probes are tested against a local fake proxy HTTP server.
"""
from __future__ import annotations

import http.server
import threading

import pytest

from app.utils import net_proxy


# ── helpers ─────────────────────────────────────────────────────────────────

class _FakeProxyHandler(http.server.BaseHTTPRequestHandler):
    """Answers 200 to any GET — stands in for a Clash HTTP proxy."""

    def do_GET(self):  # noqa: N802
        body = b"\x89PNG fake"
        self.send_response(200)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, *a):  # silence
        pass


@pytest.fixture()
def fake_proxy():
    srv = http.server.HTTPServer(("127.0.0.1", 0), _FakeProxyHandler)
    th = threading.Thread(target=srv.serve_forever, daemon=True)
    th.start()
    yield "127.0.0.1", srv.server_address[1]
    srv.shutdown()


@pytest.fixture(autouse=True)
def _reset_cache():
    net_proxy._reset_for_tests()
    yield
    net_proxy._reset_for_tests()


# ── env var parsing ──────────────────────────────────────────────────────────

class TestProxyFromEnv:
    def test_https_proxy_wins(self, monkeypatch):
        monkeypatch.setenv("https_proxy", "http://10.0.0.1:7890")
        monkeypatch.setenv("http_proxy", "http://10.0.0.2:7890")
        assert net_proxy.proxy_from_env() == "http://10.0.0.1:7890"

    def test_http_proxy_fallback(self, monkeypatch):
        monkeypatch.delenv("https_proxy", raising=False)
        monkeypatch.delenv("HTTPS_PROXY", raising=False)
        monkeypatch.setenv("http_proxy", "http://10.0.0.2:7892")
        assert net_proxy.proxy_from_env() == "http://10.0.0.2:7892"

    def test_socks_only_ignored(self, monkeypatch):
        # urllib cannot speak socks5 — a socks-only env must not be returned.
        for var in ("https_proxy", "HTTPS_PROXY", "http_proxy", "HTTP_PROXY"):
            monkeypatch.delenv(var, raising=False)
        monkeypatch.setenv("all_proxy", "socks5://10.0.0.1:7890")
        assert net_proxy.proxy_from_env() is None

    def test_empty_env_none(self, monkeypatch):
        for var in ("https_proxy", "HTTPS_PROXY", "http_proxy", "HTTP_PROXY",
                    "all_proxy", "ALL_PROXY"):
            monkeypatch.delenv(var, raising=False)
        assert net_proxy.proxy_from_env() is None


# ── gateway / nameserver parsing (pure) ──────────────────────────────────────

class TestHostDiscovery:
    def test_gateway_from_proc(self):
        # 192.168.96.1 little-endian hex = 0160A8C0
        text = (
            "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\n"
            "eth0\t00000000\t0160A8C0\t0003\t0\t0\t0\t00000000\t0\t0\t0\n"
            "eth0\t0060A8C0\t00000000\t0001\t0\t0\t0\t00F0FFFF\t0\t0\t0\n"
        )
        assert net_proxy._gateway_from_proc(text) == "192.168.96.1"

    def test_gateway_missing_returns_none(self):
        assert net_proxy._gateway_from_proc("Iface\tDestination\tGateway\n") is None

    def test_nameserver_from_resolv(self):
        text = "# generated by WSL\nnameserver 10.255.255.254\nsearch lan\n"
        assert net_proxy._nameserver_from_resolv(text) == "10.255.255.254"

    def test_candidate_hosts_dedup_and_localhost_first(self, monkeypatch):
        monkeypatch.setattr(net_proxy, "_gateway_from_proc", lambda t: "192.168.96.1")
        monkeypatch.setattr(net_proxy, "_nameserver_from_resolv", lambda t: "192.168.96.1")
        monkeypatch.setattr(net_proxy, "_read_quiet", lambda p: "x")
        hosts = net_proxy.candidate_hosts()
        assert hosts[0] == "127.0.0.1"
        assert hosts.count("192.168.96.1") == 1


# ── probe against a local fake proxy ─────────────────────────────────────────

class TestProbe:
    def test_fetch_ok_via_fake_proxy(self, fake_proxy):
        host, port = fake_proxy
        ok = net_proxy._fetch_ok(
            "http://tile.invalid/2/0/0.png", f"http://{host}:{port}", timeout=3,
        )
        assert ok is True

    def test_fetch_ok_closed_port_false(self):
        ok = net_proxy._fetch_ok(
            "http://tile.invalid/2/0/0.png", "http://127.0.0.1:1", timeout=1,
        )
        assert ok is False

    def test_port_open(self, fake_proxy):
        host, port = fake_proxy
        assert net_proxy._port_open(host, port) is True
        assert net_proxy._port_open("127.0.0.1", 1) is False


# ── detection state machine ──────────────────────────────────────────────────

class TestDetect:
    def test_env_proxy_short_circuits(self, monkeypatch):
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: "http://e:1")
        calls = []
        monkeypatch.setattr(net_proxy, "_fetch_ok", lambda *a, **k: calls.append(a) or True)
        assert net_proxy.detect_osm_proxy(force=True) == "http://e:1"
        assert calls == []  # no probing when env already routes

    def test_direct_reachable_returns_none(self, monkeypatch):
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: None)
        monkeypatch.setattr(net_proxy, "_fetch_ok",
                            lambda url, proxy, timeout=5: proxy is None)
        assert net_proxy.detect_osm_proxy(force=True) is None

    def test_blocked_direct_finds_local_proxy(self, monkeypatch, fake_proxy):
        host, port = fake_proxy
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: None)
        monkeypatch.setattr(net_proxy, "candidate_hosts", lambda: [host])
        monkeypatch.setattr(net_proxy, "_PROBE_PORTS", (port,))
        # direct fetch fails, via-proxy fetch succeeds
        monkeypatch.setattr(net_proxy, "_fetch_ok",
                            lambda url, proxy, timeout=5: proxy is not None)
        assert net_proxy.detect_osm_proxy(force=True) == f"http://{host}:{port}"

    def test_nothing_found_returns_none(self, monkeypatch):
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: None)
        monkeypatch.setattr(net_proxy, "candidate_hosts", lambda: ["127.0.0.1"])
        monkeypatch.setattr(net_proxy, "_PROBE_PORTS", (1,))
        monkeypatch.setattr(net_proxy, "_fetch_ok", lambda *a, **k: False)
        assert net_proxy.detect_osm_proxy(force=True) is None

    def test_result_cached(self, monkeypatch):
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: "http://e:1")
        assert net_proxy.detect_osm_proxy(force=True) == "http://e:1"
        monkeypatch.setattr(net_proxy, "proxy_from_env", lambda: None)
        # cached — env change after detection must not re-probe
        assert net_proxy.detect_osm_proxy() == "http://e:1"

    def test_osm_proxy_nonblocking_before_detection(self):
        # before any detection ran, osm_proxy() must return None instantly
        assert net_proxy.osm_proxy() is None
