"""theme.py — Design token system extracted from web prototype styles.css.

Colors are taken from the :root CSS variables (deep teal/cyan scientific tool palette).
build_qss() generates a complete Qt stylesheet string.
build_theme_qss_file() writes resources/theme.qss for use with app.setStyleSheet.
"""

from __future__ import annotations
from pathlib import Path

# ── Design tokens (mirror CSS :root variables) ────────────────────────────

TOKENS: dict[str, str] = {
    # Backgrounds
    "bg": "#08161b",
    "panel": "#10242a",
    "panel_2": "#0b2025",
    "modal_surface": "#10282e",
    "modal_surface_raised": "#143139",

    # Text
    "text": "#edf2ee",
    "muted": "#87a2a1",

    # Accent (teal/cyan)
    "accent": "#29b9ab",
    "accent_hover": "#31d4c4",
    "accent_pressed": "#1f9288",

    # Semantic
    "warn": "#f1bd57",
    "success": "#36c98f",
    "danger": "#e66e63",

    # Borders
    "border": "rgba(145, 182, 181, 0.13)",
    "border_medium": "rgba(145, 182, 181, 0.25)",
    "border_strong": "rgba(152, 205, 198, 0.38)",

    # Nav
    "nav_bg": "#091e24",
    "nav_selected_bg": "#12313a",
    "nav_selected_border": "#29b9ab",

    # Status bar
    "statusbar_bg": "#091e24",

    # Input
    "input_bg": "#0c2028",
    "input_border": "rgba(145, 182, 181, 0.22)",
    "input_focus_border": "#29b9ab",

    # Scrollbar
    "scrollbar_bg": "#08161b",
    "scrollbar_handle": "#1e3d47",
    "scrollbar_handle_hover": "#29b9ab",

    # Typography scale (sp)
    "font_xs": "11px",
    "font_sm": "12px",
    "font_body": "13px",
    "font_md": "14px",
    "font_lg": "16px",
    "font_title": "18px",

    # Spacing / radius
    "radius": "8px",
    "radius_sm": "5px",
    "radius_lg": "12px",
}

# Font families — preference order for CJK + Latin
_SANS_FONTS = (
    "Noto Sans SC", "Source Han Sans SC", "Noto Sans CJK SC",
    "Microsoft YaHei", "PingFang SC", "Segoe UI", "sans-serif"
)
_MONO_FONTS = ("JetBrains Mono", "Cascadia Code", "Consolas", "monospace")


def _font_family(fonts: tuple[str, ...]) -> str:
    return ", ".join(f'"{f}"' if " " in f else f for f in fonts)


def build_qss() -> str:
    """Generate a complete Qt stylesheet (QSS) from TOKENS."""
    t = TOKENS
    sans = _font_family(_SANS_FONTS)
    mono = _font_family(_MONO_FONTS)

    return f"""
/* ══════════════════════════════════════════════════════════════════
   Specimen Photo Workbench — Deep Teal Theme
   Auto-generated by app/config/theme.py — do not hand-edit
   ══════════════════════════════════════════════════════════════════ */

/* ── Global ─────────────────────────────────────────────────────── */
QWidget {{
    background-color: {t["bg"]};
    color: {t["text"]};
    font-family: {sans};
    font-size: {t["font_body"]};
    selection-background-color: {t["accent"]};
    selection-color: {t["bg"]};
}}

QMainWindow {{
    background-color: {t["bg"]};
}}

/* ── Navigation sidebar ──────────────────────────────────────────── */
QListWidget#NavList {{
    background-color: {t["nav_bg"]};
    border: none;
    border-right: 1px solid {t["border"]};
    outline: none;
    padding: 8px 0;
}}

QListWidget#NavList::item {{
    color: {t["muted"]};
    padding: 10px 16px;
    border-left: 3px solid transparent;
    border-radius: 0;
    font-size: {t["font_body"]};
}}

QListWidget#NavList::item:hover {{
    background-color: {t["nav_selected_bg"]};
    color: {t["text"]};
}}

QListWidget#NavList::item:selected {{
    background-color: {t["nav_selected_bg"]};
    color: {t["accent"]};
    border-left: 3px solid {t["nav_selected_border"]};
    font-weight: 600;
}}

/* ── Stacked / content area ──────────────────────────────────────── */
QStackedWidget {{
    background-color: {t["bg"]};
    border: none;
}}

/* ── Status bar ──────────────────────────────────────────────────── */
QStatusBar {{
    background-color: {t["statusbar_bg"]};
    color: {t["muted"]};
    border-top: 1px solid {t["border"]};
    font-size: {t["font_sm"]};
    padding: 2px 8px;
}}

QStatusBar::item {{
    border: none;
}}

QLabel#StatusSegment {{
    color: {t["muted"]};
    padding: 0 10px;
    font-size: {t["font_sm"]};
}}

QLabel#StatusSegmentAccent {{
    color: {t["accent"]};
    padding: 0 10px;
    font-size: {t["font_sm"]};
}}

/* ── Panels and cards ────────────────────────────────────────────── */
QFrame#Panel {{
    background-color: {t["panel"]};
    border: 1px solid {t["border"]};
    border-radius: {t["radius"]};
}}

QFrame#Card {{
    background-color: {t["panel_2"]};
    border: 1px solid {t["border"]};
    border-radius: {t["radius_sm"]};
}}

/* ── Labels ──────────────────────────────────────────────────────── */
QLabel {{
    background: transparent;
    color: {t["text"]};
}}

QLabel#Muted {{
    color: {t["muted"]};
}}

QLabel#Accent {{
    color: {t["accent"]};
}}

QLabel#Title {{
    font-size: {t["font_title"]};
    font-weight: 700;
    color: {t["text"]};
}}

QLabel#Section {{
    font-size: {t["font_md"]};
    font-weight: 600;
    color: {t["text"]};
    letter-spacing: 0.3px;
}}

QLabel#Placeholder {{
    color: {t["muted"]};
    font-size: {t["font_lg"]};
    font-style: italic;
}}

/* ── Buttons ─────────────────────────────────────────────────────── */
QPushButton {{
    background-color: {t["panel"]};
    color: {t["text"]};
    border: 1px solid {t["border_medium"]};
    border-radius: {t["radius_sm"]};
    padding: 6px 14px;
    font-size: {t["font_body"]};
    font-weight: 500;
}}

QPushButton:hover {{
    background-color: {t["nav_selected_bg"]};
    border-color: {t["border_strong"]};
    color: {t["text"]};
}}

QPushButton:pressed {{
    background-color: {t["modal_surface_raised"]};
}}

QPushButton:disabled {{
    color: {t["muted"]};
    border-color: {t["border"]};
}}

QPushButton#Primary {{
    background-color: {t["accent"]};
    color: {t["bg"]};
    border: none;
    font-weight: 600;
}}

QPushButton#Primary:hover {{
    background-color: {t["accent_hover"]};
}}

QPushButton#Primary:pressed {{
    background-color: {t["accent_pressed"]};
}}

QPushButton#Danger {{
    background-color: transparent;
    color: {t["danger"]};
    border: 1px solid {t["danger"]};
}}

QPushButton#Danger:hover {{
    background-color: {t["danger"]};
    color: {t["text"]};
}}

/* ── Inputs ──────────────────────────────────────────────────────── */
QLineEdit, QTextEdit, QPlainTextEdit {{
    background-color: {t["input_bg"]};
    color: {t["text"]};
    border: 1px solid {t["input_border"]};
    border-radius: {t["radius_sm"]};
    padding: 5px 10px;
    font-size: {t["font_body"]};
    selection-background-color: {t["accent"]};
    selection-color: {t["bg"]};
}}

QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
    border-color: {t["input_focus_border"]};
    outline: none;
}}

QLineEdit:disabled {{
    color: {t["muted"]};
    background-color: {t["bg"]};
}}

/* ── ComboBox ────────────────────────────────────────────────────── */
QComboBox {{
    background-color: {t["input_bg"]};
    color: {t["text"]};
    border: 1px solid {t["input_border"]};
    border-radius: {t["radius_sm"]};
    padding: 5px 10px;
    font-size: {t["font_body"]};
}}

QComboBox:focus {{
    border-color: {t["input_focus_border"]};
}}

QComboBox::drop-down {{
    border: none;
    width: 24px;
}}

QComboBox QAbstractItemView {{
    background-color: {t["panel"]};
    color: {t["text"]};
    border: 1px solid {t["border_medium"]};
    selection-background-color: {t["nav_selected_bg"]};
    selection-color: {t["accent"]};
}}

/* ── Scrollbars ──────────────────────────────────────────────────── */
QScrollBar:vertical {{
    background: {t["scrollbar_bg"]};
    width: 8px;
    margin: 0;
    border: none;
}}

QScrollBar::handle:vertical {{
    background: {t["scrollbar_handle"]};
    border-radius: 4px;
    min-height: 24px;
}}

QScrollBar::handle:vertical:hover {{
    background: {t["scrollbar_handle_hover"]};
}}

QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0;
}}

QScrollBar:horizontal {{
    background: {t["scrollbar_bg"]};
    height: 8px;
    margin: 0;
    border: none;
}}

QScrollBar::handle:horizontal {{
    background: {t["scrollbar_handle"]};
    border-radius: 4px;
    min-width: 24px;
}}

QScrollBar::handle:horizontal:hover {{
    background: {t["scrollbar_handle_hover"]};
}}

QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0;
}}

/* ── Splitter ────────────────────────────────────────────────────── */
QSplitter::handle {{
    background-color: {t["border"]};
}}

QSplitter::handle:horizontal {{
    width: 1px;
}}

QSplitter::handle:vertical {{
    height: 1px;
}}

/* ── Menu / MenuBar ──────────────────────────────────────────────── */
QMenuBar {{
    background-color: {t["nav_bg"]};
    color: {t["muted"]};
    border-bottom: 1px solid {t["border"]};
    font-size: {t["font_body"]};
}}

QMenuBar::item:selected {{
    background-color: {t["nav_selected_bg"]};
    color: {t["text"]};
}}

QMenu {{
    background-color: {t["panel"]};
    color: {t["text"]};
    border: 1px solid {t["border_medium"]};
    border-radius: {t["radius_sm"]};
    padding: 4px 0;
}}

QMenu::item {{
    padding: 6px 20px;
}}

QMenu::item:selected {{
    background-color: {t["nav_selected_bg"]};
    color: {t["accent"]};
}}

QMenu::separator {{
    height: 1px;
    background-color: {t["border"]};
    margin: 4px 8px;
}}

/* ── ToolTip ─────────────────────────────────────────────────────── */
QToolTip {{
    background-color: {t["panel"]};
    color: {t["text"]};
    border: 1px solid {t["border_medium"]};
    border-radius: {t["radius_sm"]};
    padding: 4px 8px;
    font-size: {t["font_sm"]};
}}

/* ── Table / List ────────────────────────────────────────────────── */
QTableWidget, QTableView, QListView, QTreeView {{
    background-color: {t["bg"]};
    color: {t["text"]};
    border: 1px solid {t["border"]};
    gridline-color: {t["border"]};
    alternate-background-color: {t["panel_2"]};
    selection-background-color: {t["nav_selected_bg"]};
    selection-color: {t["accent"]};
}}

QHeaderView::section {{
    background-color: {t["panel"]};
    color: {t["muted"]};
    border: none;
    border-bottom: 1px solid {t["border"]};
    padding: 5px 10px;
    font-size: {t["font_sm"]};
    font-weight: 600;
    letter-spacing: 0.4px;
}}

/* ── Tab bar ─────────────────────────────────────────────────────── */
QTabBar::tab {{
    background-color: transparent;
    color: {t["muted"]};
    border: none;
    border-bottom: 2px solid transparent;
    padding: 8px 16px;
    font-size: {t["font_body"]};
}}

QTabBar::tab:selected {{
    color: {t["accent"]};
    border-bottom: 2px solid {t["accent"]};
}}

QTabBar::tab:hover {{
    color: {t["text"]};
}}

QTabWidget::pane {{
    background-color: {t["bg"]};
    border: 1px solid {t["border"]};
    border-radius: {t["radius"]};
}}

/* ── GroupBox ────────────────────────────────────────────────────── */
QGroupBox {{
    color: {t["muted"]};
    border: 1px solid {t["border"]};
    border-radius: {t["radius"]};
    margin-top: 20px;
    padding-top: 10px;
    font-size: {t["font_sm"]};
    font-weight: 600;
    letter-spacing: 0.5px;
    text-transform: uppercase;
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 6px;
    left: 12px;
    top: 8px;
    color: {t["muted"]};
}}

/* ── CheckBox / RadioButton ──────────────────────────────────────── */
QCheckBox, QRadioButton {{
    color: {t["text"]};
    spacing: 6px;
    font-size: {t["font_body"]};
}}

QCheckBox::indicator, QRadioButton::indicator {{
    width: 15px;
    height: 15px;
    border: 1px solid {t["border_medium"]};
    border-radius: 3px;
    background-color: {t["input_bg"]};
}}

QCheckBox::indicator:checked {{
    background-color: {t["accent"]};
    border-color: {t["accent"]};
}}

/* ── Monospace label (file paths, UIDs) ──────────────────────────── */
QLabel#Mono {{
    font-family: {_font_family(_MONO_FONTS)};
    font-size: {t["font_sm"]};
    color: {t["accent"]};
    background-color: {t["modal_surface"]};
    border-radius: {t["radius_sm"]};
    padding: 2px 6px;
}}
"""


_QSS_OUTPUT = Path(__file__).parent.parent.parent / "resources" / "theme.qss"


def build_theme_qss_file() -> Path:
    """Write theme.qss to resources/ and return its path."""
    _QSS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _QSS_OUTPUT.write_text(build_qss(), encoding="utf-8")
    return _QSS_OUTPUT
